pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('AWS'){
            agent{
                docker{
                    image 'amazon/aws-cli'
                    args "--entrypoints=''"
                }
            }
            steps{
                sh '''
                    aws --version 
                    aws s3 ls
                  '''
            }
        }
    }
}
